site_name: algo
use_directory_urls: True
nav:
  - jiyun: jiyun/jiyun.md
  - 基础:
    - PB : basic/pb.md
    - Cache : basic/cache.md
    - golang:
      - Lock : basic/lock.md
      - sync.map : basic/syncmap.md
      - sync.pool: index.md
      - sync.waitgroup: index.md
      - singleflight: index.md
      - benchmark: index.md
      - ants.Pool: index.md
      - defer/panic/recover: basic/golang/panic.md
      - chan: index.md
    - json: hub/json.md
    - redis:
      - pipeline: basic/redis/pipeline.md
    - mysql: 
      - 分页算法: basic/mysql/page.md
      - 知识点: basic/mysql/point.md
    - mongo: index.md
    - kafka: basic/kafka.md
    - flink:
      - DatasStreamAPI: basic/flink/datastreamapi.md
      - StateBackEnd: basic/flink/statebackend.md
    - docker:
      - useage: basic/docker/useage.md
    - git: basic/git/useage.md
    - 应用层协议:
      - HTTP: index.md
      - TLS: index.md
      - WebSocket: index.md
    - 网络层协议:
      - 连接层协议:
        - TCP: index.md
      - 网络层协议:
        - 安全组: index.md
        - socket: basic/ip/socket.md
        - anycast: basic/ip/anycast.md
   

theme:
  name: material
  logo: "images/logo.png"
  favicon: "images/logo.png"
  custom_dir: "docs/overrides"
  features:
    - content.code.annotate
    - search.share
    - content.code.copy
    - navigation.top
    - navigation.footer
  palette:
    - scheme: default
      primary: "blue grey"
      accent: "tear"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: "blue grey"
      accent: "tear"
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
extra_css:
  - "stylesheets/ft.extra.css"
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.pathconverter
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: docs
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - mdx_truly_sane_lists
