site_name: WAF
use_directory_urls: True
nav:
    - 概览: index.md
    - 未完成整理: todo.md
    - 控制面:
      - API: 
        - 防范sqlinject: console/api/sqlinject.md
        - log: console/api/log.md
        - 数据生命周期管理: console/api/lifecycle.md
        - Gate2.0: console/api/gate2_0.md
      - trpc: 
        - 插件设计: console/trpc/plugin.md
    - 接入:
      - 发展历程: access/access.md
      - SAAS-WAF:
        - DNS: access/saas/dns.md
        - 四层负载均衡: index.md
        - 自研上云:
          - 从1.0到1.5的waf设计: access/saas/group/design.md
          - 组件改造: access/saas/group/rebuild.md
          - 迁移方案: access/saas/group/transfer.md
          - 性能和成本: access/saas/group/performance.md
          - tke: access/saas/group/tke.md
        - 过载保护:
          - 统计: access/saas/limit/count.md
          - 带宽限速: access/saas/limit/bandlimit.md
          - 沙箱策略: access/saas/limit/sandbox.md
          - 单机过载保护: access/saas/limit/rslimit.md
          - 一键bypass: access/saas/limit/bypass.md
        - IPV6: 
          - 技术方案: access/saas/ipv6/method.md
          - 知识栈: access/saas/ipv6/ipv6stack.md
        - 安全组:
          - 一键放通: access/saas/sg/auto.md
          - netfilter: access/saas/sg/netfilter.md
        - TLS版本定制:
          - 需求: access/saas/tls/demand.md
        - 杂项:
          - sni: access/saas/others/sni.md
          - ssrf: access/saas/others/ssrf.md
        - 项目总结: index.md
      - CLB-WAF:
        - 七层负载均衡: index.md
        - 负载均衡接入WAF: index.md
        - 项目总结: index.md
      - WX-WAF:
        - 小程序/Donut/WAF: access/wx/miniprogram.md
        - Donut接入WAF: access/wx/wafaccess.md
        - 项目总结: access/wx/summary.md
        - 茶百道: access/wx/chabaidao.md
      - TCE-WAF:
        - tce: index.md
      - 接入引擎:
        - NGINX: 
          - cache: access/engine/nginx/cache.md
        - LUA: 
          - init: access/engine/lua/init.md
          - rewrite: access/engine/lua/rewrite.md
          - access: access/engine/lua/access.md
          - filter: access/engine/lua/filter.md
          - log: access/engine/lua/log.md
    - 防护:
      - HUB:
        - 设计: hub/desgin.md
        - TRPC: index.md
        - FastHttp: index.md
        - polaris: 
          - hash路由: index.md
          - 监控上报: index.md
        - GC: 
          - ballast: index.md
        - monitor: 
          - pprof: index.md
        - 项目总结: hub/summary.md
      - 基础安全:
        - WEB安全:
          - WEB攻击: security/basic/web/attack.md
          - 规则引擎: index.md
          - AI引擎: index.md
        - 访问控制:
          - 地域封禁: index.md
          - 自定义规则: index.md
        - cc防护:
          - 自定义CC: index.md
          - 智能紧急CC: index.md
        - 网页防篡改: 
          - 设计: security/basic/antitamper/design.md
          - srcache: security/basic/antitamper/srcache.md
        - 信息防泄漏: index.md
        - 验证码: index.md
        - 腾讯云DDOS: secury/basic/ddos.md
      - BOT管理: 
        - 功能设计: 
          - 需求背景: bot/background.md
          - 功能细化: bot/feature.md
          - 架构设计: bot/desgin.md
        - 功能实现:
          - BOT特征提取: bot/botfeature.md
          - BOT执行器: bot/botexecutor.md
          - BOTAI执行器: bot/botaiexecutor.md
        - 其他思路:
          - 科恩实验室: bot/keen.md
      - API安全:
        - API安全: index.md
        - API限流: index.md
    - 日志:
      - lua上传日志: logs/lua.md
      - log-syncer: index.md
      - ElasticSearch:
        - ES: index.md
      - ClickHouse:
        - CK: index.md
      - KafKa:
        - kafka: index.md
    - TADK : 
      - chapter1: tadk/chapter1.md
    - 基础:
      - 正则表达式: basic/regex/regex.md
      - PB: basic/pb.md
      - Cache: basic/cache.md
      - golang:
        - 包管理: basic/golang/package.md
        - Lock: basic/golang/lock.md
        - sync.map: basic/golang/syncmap.md
        - sync.pool: index.md
        - sync.waitgroup: index.md
        - singleflight: index.md
        - benchmark: index.md
        - ants.Pool: index.md
        - defer/panic/recover: basic/golang/panic.md
        - chan: index.md
        - container: basic/golang/container.md
      - json: hub/json.md
      - redis:
        - pipeline: basic/redis/pipeline.md
      - mysql: 
        - 分页算法: basic/mysql/page.md
        - metadatalock: basic/mysql/metadatalock.md
        - 知识点: basic/mysql/point.md
      - mongo: index.md
      - kafka: basic/kafka/kafka.md
      - flink:
        - DatasStreamAPI: basic/flink/datastreamapi.md
        - StateBackEnd: basic/flink/statebackend.md
      - docker:
        - useage: basic/docker/useage.md
      - git: basic/git/useage.md
      - 网络:
        - 应用层协议:
          - HTTP: basic/network/http/http.md
          - TLS: basic/network/http/tls.md
          - 回话保持/身份认证: basic/network/http/cookie_token.md
          - 基于HTTP的追加协议: basic/network/http/http_append.md
        - 连接层协议:
          - TCP: index.md
        - 网络层协议:
          - 安全组: index.md
          - socket: basic/network/ip/socket.md
          - anycast: basic/network/ip/anycast.md
        - 报文生产: basic/network/frame.md
      - OS:
        - shell: basic/os/shell.md



theme:
  name: material
  logo: "images/logo.png"
  favicon: "images/logo.png"
  custom_dir: "docs/overrides"
  features:
    - content.code.annotate
    - search.share
    - content.code.copy
    - navigation.top
    - navigation.footer
  palette:
    - scheme: default
      primary: "blue grey"
      accent: "tear"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: "blue grey"
      accent: "tear"
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
extra_css:
  - "stylesheets/ft.extra.css"
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.pathconverter
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: docs
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - mdx_truly_sane_lists
