site_name: LUCASLI
use_directory_urls: True
nav:
    - Hi: index.md
    - 简历:
      - 量化: cv/量化开发_李仁杰_15622300793.html
      - AI: cv/AI开发_李仁杰_15622300793.html
      - 后台: cv/后台开发_李仁杰_15622300793.html
    - 项目总结: prjectintro.md
    - 经历介绍: jobintro.md
    - WAF控制面:
      - API: 
        - 防范sqlinject: console/api/sqlinject.md
        - log: console/api/log.md
        - 数据生命周期管理: console/api/lifecycle.md
        - Gate2.0: console/api/gate2_0.md
        - ssrf: console/api/ssrf.md
        - fastcgi: console/api/fastcgi.md
        - 服务票据: console/api/ticket.md
        - 程序可观测性: console/api/observability.md
      - trpc: 
        - 设计: console/trpc/design.md
        - 插件设计: console/trpc/plugin.md
    - WAF接入:
      - 发展历程: access/access.md
      - SAAS-WAF:
        - DNS: access/saas/dns.md
        - 四层负载均衡: 
          - LVS: access/saas/lb/lvs.md
          - IPIP-GRE: access/saas/lb/ipipgre.md
          - tvs-ko: access/saas/lb/tvs-ko.md
        - 自研上云:
          - 设计: access/saas/group/design.md
          - 组件改造: access/saas/group/rebuild.md
          - 迁移方案: access/saas/group/transfer.md
          - 性能和成本: access/saas/group/performance.md
          - tke: access/saas/group/tke.md
          - WAF云原生之路: access/saas/group/waytocloudnative.md
        - 过载保护:
          - 135项目: access/saas/limit/135.md
          - 统计: access/saas/limit/count.md
          - 带宽限速: access/saas/limit/bandlimit.md
          - 沙箱策略: access/saas/limit/sandbox.md
          - 单机过载保护: access/saas/limit/rslimit.md
          - 一键bypass: access/saas/limit/bypass.md
          - ipset-cc: access/saas/limit/ipsetcc.md
        - IPV6: 
          - 技术方案: access/saas/ipv6/method.md
          - 知识栈: access/saas/ipv6/ipv6stack.md
        - 安全组:
          - 一键放通: access/saas/sg/auto.md
          - netfilter: access/saas/sg/netfilter.md
        - TLS定制:
          - 需求: access/saas/tls/demand.md
          - 技术方案: access/saas/tls/tech.md
          - 证书: access/saas/tls/gm.md
          - 加密套件优先级: access/saas/tls/priority.md
          - 加密套件身份认证: access/saas/tls/auth.md
        - 热加载:
          - 实现方案: access/saas/hotload/method.md
      - CLB-WAF:
        - 负载均衡接入WAF: access/clb/clbwaf.md
      - WX-WAF:
        - 小程序/Donut/WAF: access/wx/miniprogram.md
        - Donut接入WAF: access/wx/wafaccess.md
        - 项目总结: access/wx/summary.md
        - 茶百道: access/wx/chabaidao.md
      - TCE-WAF:
        - tce: access/saas/tce/tce.md
      - 腾讯云网络: access/net/tencentcloudnet.md
      - EdgeOne: access/edgeone/edgeone.md
      - 接入引擎:
        - NGINX: 
          - 编译: access/engine/nginx/compile.md
          - sni: access/engine/nginx/sni.md
          - cache: access/engine/nginx/cache.md
          - event: access/engine/nginx/event.md
          - 健康检测: access/engine/nginx/health.md
          - TLSSessionTicket: access/engine/nginx/tlsst.md
          - realip: access/engine/nginx/realip.md
          - limitrate: access/engine/nginx/limitrate.md
          - 透明代理: access/engine/nginx/transparent.md
          - 单端口提供HTTP和HTTPS服务: access/engine/nginx/httpwithhttps.md  
          - proxy_protocol: access/engine/nginx/proxyprotocol.md
          - http配置解析: access/engine/nginx/httpconfig.md
          - 共享内存: access/engine/nginx/shm.md
          - 正则匹配: access/engine/nginx/regex.md
          - 架构第一章: access/engine/nginx/arch.md
          - 架构第二章: access/engine/nginx/arch1.md
          - 连接池内存池: access/engine/nginx/pool.md
        - LUA: 
          - init: access/engine/lua/init.md
          - rewrite: access/engine/lua/rewrite.md
          - access: access/engine/lua/access.md
          - filter: access/engine/lua/filter.md
          - log: access/engine/lua/log.md
          - 性能优化: access/engine/lua/pprof.md
        - openresty: 
          - basic: access/engine/openresty/openresty.md
          - luajit: access/engine/openresty/luajit.md
          - api: access/engine/openresty/api.md
          - 线程模型: access/engine/openresty/thread.md
    - WAF防护:
      - 概览: security/overview.md
      - HUB:
        - 需求分析/设计: security/hub/desgin.md
        - 性能优化: 
          - 优化概览: security/hub/pprof.md
          - GC/内存优化: security/hub/mem_pprof.md
          - 执行速度优化: security/hub/speed_pprof.md
          - I/O优化: security/hub/io_pprof.md
          - 内核调参: security/hub/kernel_pprof.md
        - polaris服务治理:
          - polaris简介: security/hub/service/polaris.md
          # - 服务注册与发现: security/hub/service/registry.md
          - 服务调用: security/hub/service/call.md
          - 服务监控: security/hub/service/monitor.md
        - 服务部署:
          - 服务部署: security/hub/service/deploy.md
        - 案例:
          - 小红书: security/hub/xiaohongshu.md
      - 基础安全:
        - WEB安全:
          - WEB攻击: security/basic/web/attack.md
          - 规则引擎: security/basic/web/rules.md
          - AI引擎: security/basic/web/ai.md
          - 访问控制: security/basic/web/access_limit.md
        - cc防护:
          # - 自定义CC: index.md
          # - 智能紧急CC: index.md
          - ipset-cc: access/saas/limit/ipsetcc.md
        - 网页防篡改: 
          - 设计: security/basic/antitamper/design.md
          - srcache: security/basic/antitamper/srcache.md
        - 信息防泄漏: access/engine/lua/filter.md
        - 资源防盗链: security/basic/antilink/antilink.md
        - 验证码: security/basic/captcha/captcha.md
        - 腾讯云DDOS: security/basic/ddos.md
      - BOT管理: 
        - 功能设计: 
          - 需求背景: bot/background.md
          - 功能细化: bot/feature.md
          - 架构设计: bot/desgin.md
          - 用户体验: bot/use.md
        - 功能实现:
          - BOT特征提取: bot/botfeature.md
          - BOT执行器: bot/botexecutor.md
          - BOTAI执行器: bot/botaiexecutor.md
        - 其他思路:
          - 科恩实验室: bot/keen.md
        - 技术相关: 
          - flink构建ClickHouse实时数仓: bot/tech/flink_clickhouse.md
      # - API安全:
      #   - API安全: index.md
      #   - API限流: index.md
      - research: 
        - 基于DL的Payload检测: security/research/dl.md
        - 基于DNN的cc检测: security/research/dnn.md
        - 基于GD的SVM模型推导: security/research/svm.md
    - WAF日志:
      - lua上传日志: logs/lua.md
      - kafka: 
        - producer: logs/kafka/producer.md
        - consumer: logs/kafka/consumer.md
      - elasticsearch: 
        - 使用: basic/es/useage.md
        - 基础: basic/es/es.md
        - 索引: basic/es/index.md
      - clickhouse: 
        - 基础: basic/clickhouse/clickhouse.md
    - WAF问题排查:
      - cpu100问题: problem/cpu100.md
      - coredump问题: problem/coredump.md
    - 基础知识积累:
      - 正则表达式: basic/regex/regex.md
      - wrk: basic/test/wrk.md
      - PB: basic/pb.md
      - Cache: basic/cache.md
      - python:
        - jupyter: basic/python/jupyter.md
        - python核心与技术: basic/python/basic.md
        - interview-1: basic/python/interview-1.md
      - golang:
        - 基本类型: basic/golang/type.md
        - benchmark: basic/golang/benchmark.md
        - 包管理: basic/golang/package.md
        - 版本管理: basic/golang/goversion.md
        - lock: basic/golang/lock.md
        - map: basic/golang/map.md
        - sync.map: basic/golang/syncmap.md
        - sync.pool: basic/golang/syncpool.md
        - sync.waitgroup: basic/golang/syncwaitgroup.md
        - defer/panic/recover: basic/golang/panic.md
        - chan: basic/golang/chan.md
        - container: basic/golang/container.md
        - make/new: basic/golang/make_new.md
        - rune: basic/golang/rune.md
        - select: basic/golang/select.md
        - assert: basic/golang/assert.md
        - string/slice: basic/golang/string_slice.md
        - 垃圾回收: basic/golang/gc.md
        - 栈内存管理: basic/golang/stack.md
        - 堆内存管理: basic/golang/heap.md
        - reflect: basic/golang/reflect.md
        - 协程生命周期: basic/golang/goroutinelifecycle.md
        - log: basic/golang/log.md
        - 信号量: basic/golang/semaphore.md
        - 证书: basic/golang/cert.md
        - pprof: basic/golang/pprof.md
        - 源码:
          - m0/g0: basic/golang/sourcecode/m0_g0.md
          - 创建maing: basic/golang/sourcecode/maing.md
          - 运行maing: basic/golang/sourcecode/runmaing.md
          - 运行normalg: basic/golang/sourcecode/runnormalg.md
          - runtime通用函数: bacic/golang/sourcecode/runtime.md
      - redis:
        - point: basic/redis/point.md
        - pipeline: basic/redis/pipeline.md
        - 使用场景: basic/redis/useage.md
        - 深入: basic/redis/deep.md
        - 分布式锁: basic/redis/lock.md
      - mysql: 
        - 主从: basic/mysql/masterslave.md
        - 分页算法: basic/mysql/page.md
        - metadatalock: basic/mysql/metadatalock.md
        - 触发器: basic/mysql/trigger.md
        - 执行一条mysql发生了什么: basic/mysql/step.md
        - 知识点: basic/mysql/point.md
      - mongo: 
        - useage: basic/mongo/useage.md
      - kafka: 
        - backgroud: basic/kafka/kafka.md
        - 技术细节: basic/kafka/tech.md
      - flink:
        - DatasStreamAPI: basic/flink/datastreamapi.md
        - StateBackEnd: basic/flink/statebackend.md
      - docker:
        - useage: basic/docker/useage.md
        - 容器背景: basic/docker/background.md
        - 容器技术: basic/docker/tech.md
      - kubernetes:
        - 知识点: basic/kubernetes/point.md
        - pod调度到node: basic/kubernetes/schedule.md
      - git: basic/git/useage.md
      - network:
        - allpoint: basic/networl/allpoint.md
        - 应用层协议:
          - HTTP: basic/network/http/http.md
          - TLS: basic/network/http/tls.md
          - 基于HTTP的追加协议: basic/network/http/http_append.md
          - DNS: access/saas/dns.md
          - 回话保持/身份认证: basic/network/http/cookie_token.md
        - 连接层协议:
          - tcp: basic/network/tcp/tcp.md
          - 长链接: basic/network/tcp/keepalive.md
          - socket: basic/network/tcp/socket.md
        - 网络层协议:
          - 安全组: access/saas/sg/netfilter.md
          - anycast: basic/network/ip/anycast.md
        - 报文生成: basic/network/frame.md
        - 交换机和路由器: basic/network/switch_router.md
      - os:
        - allpoint: basic/os/allpoint.md
        - 并发模型: basic/os/concurrency.md
        - 同步互斥: basic/os/sync.md
        - 存储器管理: basic/os/mem.md
        - 中断: basic/os/break.md
        - IO: basic/os/io.md
        - Socket: basic/network/tcp/socket.md
        - shell: basic/os/shell.md
        - strace: basic/os/strace.md
        - crontab: basic/os/crontab.md
        - 芯片架构: basic/os/arch.md
        - gdb: basic/os/gdb.md
        - cow: basic/os/cow.md
        - 常见问题: basic/os/question.md
      - lib: 
        - tcmalloc: basic/lib/tcmalloc.md 
      - bigData:
        - HDFS: basic/bigdata/hdfs.md
        - mapReduce: basic/bigdata/mapreduce.md
        - yarn: basic/bigdata/yarn.md
        - hive: basic/bigdata/hive.md
        - spark: basic/bigdata/spark.md
      - es: 
        - 使用: basic/es/useage.md
        - 基础: basic/es/es.md
        - 索引: basic/es/index.md
      - clickhouse: 
        - 基础: basic/clickhouse/clickhouse.md
    - QuantDev:
      - 项目总结: quant/summary.md
      - prejob: 
        - skills: quant/prejob/skill.md
      - 框架: quant/框架.md
      - 实盘数据: quant/livedata.md
      - 金融:
        - CTA: quant/finance/CTA.md
        - 指标: quant/finance/indcator.md
        - 红利: quant/finance/红利指数.md
        - 期权: quant/finance/straddle.md
        - 债券: quant/finance/债券.md
        - 标的规划: quant/finance/投资标的.md
      - 带单项目:
        - 商业思路: quant/copytrading/商业思路.md
        - 自己带单 : quant/copytrading/copytrading.md
        - 带单点评平台: quant/copytrading/copytradig_review_platform.md
      - 量化:
        - freqtrade:
          - freqtrade安装: quant/freqtrade/freqtrade安装指南.md
          - freqtrade使用: quant/freqtrade/freqtrade使用方法.md
          - freqtrade知识点: quant/freqtrade/freqtrade_point.md
          - freqtrade实盘注意事项: quant/freqtrade/freqtrade实盘注意事项.md
          - freqtrade回测注意事项: quant/freqtrade/freqtrade回测注意事项.md
        - 知识:
          - 交易类型: quant/spot-margin-future-option.md
          - 带单交易策略: quant/knowleage/copy_trading.md
        - 策略:
          - 开发流程: quant/strategy/策略开发流程.md
          - 趋势策略:
            - 现货金三角: quant/strategy/现货金三角.md
            - 期货金三角: quant/strategy/期货金三角.md
            - 在趋势系统中如何应对震荡: quant/strategy/在趋势系统中如何应对震荡.md
          - 反转策略:
            - 突破回踩: quant/strategy/reverse-1.md
            - 突破回踩,ATR动态止盈止损: quant/strategy/reverse-2.md
            - 突破回踩均线DCA: quant/strategy/reverse-3.md
          - 粘合发散:
            - 均线粘合发散: quant/strategy/期货均线粘合发散.md
          - 因子:
            - 微盘因子: quant/strategy/小微盘选币因子.md
        - 交易工具: 
          - 网格马丁混合策略: quant/trading_tools/grid_DCA.md
          - 比例系数衰减网格策略: quant/trading_tools/grid_ratio.md
        - 贝叶斯因子挖掘和超参数调优: 
          - 关于超参数: quant/ml/关于超参数.md
          - bayesian优化: quant/ml/bayesian.md
          - epoch: quant/ml/epoch.md
        - adptive-ai-modle:
          - intro: quant/ai/intro.md
      - 书籍:
        - 量化投资_策略与技术_丁鹏:
          - 介绍: quant/quantinvestment_strategy_tech/intro.md
          - 选股: quant/quantinvestment_strategy_tech/choose.md
      - freqtrade:
        - Home: quant/index.md
        - Quickstart with Docker: quant/docker_quickstart.md
        - Installation:
            - Linux/MacOS/Raspberry: quant/installation.md
            - Windows: quant/windows_installation.md
        - Freqtrade Basics: quant/bot-basics.md
        - Configuration: quant/configuration.md
        - Strategy Customization: quant/strategy-customization.md
        - Strategy Callbacks: quant/strategy-callbacks.md
        - Stoploss: quant/stoploss.md
        - Plugins: quant/plugins.md
        - Start the bot: quant/bot-usage.md
        - Control the bot:
            - Telegram: quant/telegram-usage.md
            - REST API & FreqUI: quant/rest-api.md
            - Web Hook: quant/webhook-config.md
        - Data Downloading: quant/data-download.md
        - Backtesting: quant/backtesting.md
        - Lookahead analysis: quant/lookahead-analysis.md
        - Hyperopt: quant/hyperopt.md
        - FreqAI:
            - Introduction: quant/freqai.md
            - Configuration: quant/freqai-configuration.md
            - Parameter table: quant/freqai-parameter-table.md
            - Feature engineering: quant/freqai-feature-engineering.md
            - Running FreqAI: quant/freqai-running.md
            - Reinforcement Learning: quant/freqai-reinforcement-learning.md
            - Developer guide: quant/freqai-developers.md
        - Short / Leverage: quant/leverage.md
        - Utility Sub-commands: quant/utils.md
        - Plotting: quant/plotting.md
        - Exchange-specific Notes: quant/exchanges.md
        - Data Analysis:
            - Jupyter Notebooks: quant/data-analysis.md
            - Strategy analysis: quant/strategy_analysis_example.md
            - Backtest analysis: quant/advanced-backtesting.md
        - Advanced Topics:
            - Advanced Post-installation Tasks: quant/advanced-setup.md
            - Trade Object: quant/trade-object.md
            - Advanced Strategy: quant/strategy-advanced.md
            - Advanced Hyperopt: quant/advanced-hyperopt.md
            - Producer/Consumer mode: quant/producer-consumer.md
            - Edge Positioning: quant/edge.md
        - FAQ: quant/faq.md
        - SQL Cheat-sheet: quant/sql_cheatsheet.md
        - Strategy migration: quant/strategy_migration.md
        - Updating Freqtrade: quant/updating.md
        - Deprecated Features: quant/deprecated.md
        - Contributors Guide: quant/developer.md
theme:
  name: material
  # logo: "images/logo.png"
  # favicon: "images/logo.png"
  custom_dir: "docs/overrides"
  features:
    - content.code.annotate
    - search.share
    - content.code.copy
    - navigation.top
    - navigation.footer
  palette:
    - scheme: default
      primary: "blue grey"
      accent: "tear"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: "blue grey"
      accent: "tear"
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
extra_css:
  - "stylesheets/ft.extra.css"
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.pathconverter
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: docs
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - mdx_truly_sane_lists
