site_name: WAF
use_directory_urls: True
nav:
    - 概览: index.md
    - 未完成整理: todo.md
    - 控制面:
      - API: 
        - 防范sqlinject: console/api/sqlinject.md
        - log: console/api/log.md
        - 数据生命周期管理: console/api/lifecycle.md
        - Gate2.0: console/api/gate2_0.md
        - ssrf: access/api/ssrf.md
        - fastcgi: access/api/fastcgi.md
        - 服务票据: access/api/ticket.md
        - 程序可观测性: access/api/observability.md
      - trpc: 
        - 插件设计: console/trpc/plugin.md
    - 接入:
      - 发展历程: access/access.md
      - SAAS-WAF:
        - DNS: access/saas/dns.md
        - 四层负载均衡: 
          - LVS: access/saas/lb/lvs.md
          - IPIP-GRE: access/saas/lb/ipipgre.md
          - tvs-ko: access/saas/lb/tvs-ko.md
        - 自研上云:
          - 从1.0到1.5的waf设计: access/saas/group/design.md
          - 组件改造: access/saas/group/rebuild.md
          - 迁移方案: access/saas/group/transfer.md
          - 性能和成本: access/saas/group/performance.md
          - tke: access/saas/group/tke.md
        - 过载保护:
          - 135项目: access/saas/limit/135.md
          - 统计: access/saas/limit/count.md
          - 带宽限速: access/saas/limit/bandlimit.md
          - 沙箱策略: access/saas/limit/sandbox.md
          - 单机过载保护: access/saas/limit/rslimit.md
          - 一键bypass: access/saas/limit/bypass.md
          - ipset-cc: access/saas/limit/ipsetcc.md
        - IPV6: 
          - 技术方案: access/saas/ipv6/method.md
          - 知识栈: access/saas/ipv6/ipv6stack.md
        - 安全组:
          - 一键放通: access/saas/sg/auto.md
          - netfilter: access/saas/sg/netfilter.md
        - TLS版本定制:
          - 需求: access/saas/tls/demand.md
          - 技术方案: access/saas/tls/tech.md
          - 证书: access/saas/tls/gm.md
          - 加密套件优先级: access/saas/tls/priority.md
          - 加密套件身份认证: access/saas/tls/auth.md
        - 热加载:
          - 实现方案: access/saas/hotload/method.md
      - CLB-WAF:
        - 七层负载均衡: index.md
        - 负载均衡接入WAF: access/clb/clbwaf.md
        - 项目总结: index.md
      - WX-WAF:
        - 小程序/Donut/WAF: access/wx/miniprogram.md
        - Donut接入WAF: access/wx/wafaccess.md
        - 项目总结: access/wx/summary.md
        - 茶百道: access/wx/chabaidao.md
      - TCE-WAF:
        - tce: index.md
      - 腾讯云网络: access/net/tencentcloudnet.md
      - EdgeOne: access/edgeone/edgeone.md
      - 接入引擎:
        - NGINX: 
          - 编译: access/engine/nginx/compile.md
          - sni: access/engine/nginx/sni.md
          - cache: access/engine/nginx/cache.md
          - event: access/engine/nginx/event.md
          - 健康检测: access/engine/nginx/health.md
          - TLSSessionTicket: access/engine/nginx/tlsst.md
          - realip: access/engine/nginx/realip.md
          - limitrate: access/engine/nginx/limitrate.md
          - 透明代理: access/engine/nginx/transparent.md
          - 单端口提供HTTP和HTTPS服务: access/engine/nginx/httpwithhttps.md  
          - proxy_protocol: access/engine/nginx/proxyprotocol.md
          - http配置解析: access/engine/nginx/httpconfig.md
          - 共享内存: access/engine/nginx/shm.md
          - 正则匹配: access/engine/nginx/regex.md
          - 架构: access/engine/nginx/arch.md
          - 架构-1: access/engine/nginx/arch1.md
          - http模块: access/engine/nginx/http.md
          - 连接池内存池: access/engine/nginx/pool.md
        - LUA: 
          - init: access/engine/lua/init.md
          - rewrite: access/engine/lua/rewrite.md
          - access: access/engine/lua/access.md
          - filter: access/engine/lua/filter.md
          - log: access/engine/lua/log.md
        - openresty: 
          - basic: acess/engine/openresty/openresty.md
          - luajit: access/engine/openresty/luajit.md
          - api: access/engine/openresty/api.md
          - 线程模型: access/engine/openresty/thread.md
    - 防护:
      - HUB:
        - 设计: hub/desgin.md
        - TRPC: index.md
        - FastHttp: index.md
        - polaris: 
          - hash路由: index.md
          - 监控上报: index.md
        - GC: 
          - ballast: index.md
        - monitor: 
          - pprof: index.md
        - 项目总结: hub/summary.md
      - 基础安全:
        - WEB安全:
          - WEB攻击: security/basic/web/attack.md
          - 规则引擎: index.md
          - AI引擎: security/basic/web/ai.md
        - 访问控制:
          - 地域封禁: index.md
          - 自定义规则: index.md
        - cc防护:
          - 自定义CC: index.md
          - 智能紧急CC: index.md
        - 网页防篡改: 
          - 设计: security/basic/antitamper/design.md
          - srcache: security/basic/antitamper/srcache.md
        - 信息防泄漏: index.md
        - 资源防盗链: security/basic/antilink/antilink.md
        - 验证码: security/basic/captcha/captcha.md
        - 腾讯云DDOS: secury/basic/ddos.md
      - BOT管理: 
        - 功能设计: 
          - 需求背景: bot/background.md
          - 功能细化: bot/feature.md
          - 架构设计: bot/desgin.md
          - 体验: bot/use.md
        - 功能实现:
          - BOT特征提取: bot/botfeature.md
          - BOT执行器: bot/botexecutor.md
          - BOTAI执行器: bot/botaiexecutor.md
        - 其他思路:
          - 科恩实验室: bot/keen.md
      - API安全:
        - API安全: index.md
        - API限流: index.md
      - research: 
        - 基于DL的Payload检测: security/research/dl.md
        - 基于DNN的cc检测: security/research/dnn.md
        - 基于GD的SVM模型推导: security/research/svm.md
    - 日志:
      - lua上传日志: logs/lua.md
      - kafka: 
        - producer: logs/producer.md
        - consumer: logs/consumer.md
      - ElasticSearch:
        - ES: index.md
      - ClickHouse:
        - CK: index.md
    - 基础:
      - 正则表达式: basic/regex/regex.md
      - PB: basic/pb.md
      - Cache: basic/cache.md
      - golang:
        - 基本类型: basic/golang/type.md
        - 包管理: basic/golang/package.
        - 版本管理: basic/golang/version.md
        - Lock: basic/golang/lock.md
        - map: basic/golang/map.md
        - sync.map: basic/golang/syncmap.md
        - sync.mutex: basic/golang/syncmutex.md
        - sync.pool: index.md
        - sync.waitgroup: index.md
        - singleflight: index.md
        - benchmark: index.md
        - ants.Pool: index.md
        - defer/panic/recover: basic/golang/panic.md
        - chan: baic/golang/chan.md
        - container: basic/golang/container.md
        - make/new: basic/golang/make_new.md
        - rune: basic/golang/rune.md
        - select: basic/golang/select.md
        - assert: basic/golang/assert.md
        - string/slice: basic/golang/string_slice.md
        - 垃圾回收: basic/golang/gc.md
        - 栈内存管理: basic/golang/stack.md
        - 堆内存管理: basic/golang/heap.md
        - reflect: basic/golang/reflect.md
        - 协程生命周期: basic/golang/goroutinelifecycle.md
        - log: basic/golang/log.md
        - 信号量: basic/golang/semaphore.md
        - 证书: basic/golang/cert.md
        - 源码:
          - m0/g0: basic/golang/sourcecode/m0_g0.md
          - 创建maing: basic/golang/sourcecode/maing.md
          - 运行maing: basic/golang/sourcecode/runmaing.md
          - 运行normalg: basic/golang/sourcecode/runnormalg.md
          - runtime通用函数: bacic/golang/sourcecode/runtime.md
      - json: hub/json.md
      - redis:
        - pipeline: basic/redis/pipeline.md
        - 使用场景: basic/redis/useage.md
        - 深入: basic/redis/deep.md
        - 分布式锁: basic/redis/lock.md
      - mysql: 
        - 分页算法: basic/mysql/page.md
        - metadatalock: basic/mysql/metadatalock.md
        - 触发器: basic/mysql/trigger.md
        - 执行一条mysql发生了什么: basic/mysql/step.md
        - 知识点: basic/mysql/point.md
      - mongo: index.md
      - kafka: 
        - backgroud: basic/kafka/kafka.md
        - 技术细节: basic/kafka/tech.md
      - flink:
        - DatasStreamAPI: basic/flink/datastreamapi.md
        - StateBackEnd: basic/flink/statebackend.md
      - docker:
        - useage: basic/docker/useage.md
        - 容器背景: basic/docker/background.md
        - 容器技术: basic/docker/tech.md
      - git: basic/git/useage.md
      - 网络:
        - 应用层协议:
          - HTTP: basic/network/http/http.md
          - TLS: basic/network/http/tls.md
          - 回话保持/身份认证: basic/network/http/cookie_token.md
          - 基于HTTP的追加协议: basic/network/http/http_append.md
          - 长链接: baisc/network/http/keepalive.md
        - 连接层协议:
          - TCP: index.md
        - 网络层协议:
          - 安全组: index.md
          - socket: basic/network/ip/socket.md
          - anycast: basic/network/ip/anycast.md
        - 报文生产: basic/network/frame.md
        - 交换机和路由器: basic/network/switch_router.md
      - OS:
        - shell: basic/os/shell.md
        - strace: basic/os/strace.md
        - crontab: basic/os/crontab.md
        - 并发模型: basic/os/concurrency.md
        - 同步互斥: basic/os/sync.md
        - 芯片架构: basic/os/arch.md
        - gdb: basic/os/gdb.md
        - cow: baisc/os/cow.md
      - bigData:
        - HDFS: basic/bigData/hdfs.md
        - mapReduce: basic/bigData/mapreduce.md
        - yarn: basic/bigData/yarn.md
        - hive: basic/bigData/hive.md
        - spark: basic/bigData/spark.md
      - ES: 
        - 使用: basic/es/useage.md
        - 基础: basic/es/es.md
        - 索引: basic/es/index.md
      - clickhouse: 
        - 基础: basic/clickhouse/clickhouse.md
    - 问题排查:
      - cpu100问题: problem/cpu100.md
      - coredump问题: problem/coredump.md

theme:
  name: material
  logo: "images/logo.png"
  favicon: "images/logo.png"
  custom_dir: "docs/overrides"
  features:
    - content.code.annotate
    - search.share
    - content.code.copy
    - navigation.top
    - navigation.footer
  palette:
    - scheme: default
      primary: "blue grey"
      accent: "tear"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: "blue grey"
      accent: "tear"
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
extra_css:
  - "stylesheets/ft.extra.css"
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.pathconverter
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: docs
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - mdx_truly_sane_lists
